{% set name = "scikit-downscale" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a2980e381297866abb007ec70a74b343af58e58ac5d1ba43a54249ce450046e0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - xarray >=0.16
    - scikit-learn >=0.21

test:
  imports:
    - skdownscale

about:
  home: https://github.com/pangeo-data/scikit-downscale
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Statistical downscaling and postprocessing models for climate and weather model simulations.
  description: |
    Scikit-downscale is a toolkit for statistical downscaling usising Xarray. It is meant to
    support the development of new and existing downscaling methods in a common framework. It
    implements a fit/predict API that accepts Xarray objects, similiar to Python’s Scikit-Learn,
    for building a wide range of statitical downscaling models.
  doc_url: https://scikit-downscale.readthedocs.io
  dev_url: https://github.com/jhamman/scikit-downscale

extra:
  recipe-maintainers:
    - jhamman
    - jukent
    - andersy005
